deploy:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: python-app

    # Espera breve para evitar conflictos de despliegue simultáneo
    - name: Wait before deploy
      run: sleep 20

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      id: deploy-to-webapp
      with:
        app-name: 'spacio-object-detection'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1B1A174C872A43D7919AEC0DD4561379 }}
        package: .
        clean: true
